<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.18">
  <Itf Name="I_Sequenceable" Id="{35254ce5-31f8-47be-b042-8d89379deee8}">
    <Declaration><![CDATA[INTERFACE I_Sequenceable
]]></Declaration>
    <Method Name="Abort" Id="{73e7e51d-5188-42bb-ba19-d4208bc1d736}">
      <Declaration><![CDATA[METHOD Abort : BOOL
]]></Declaration>
    </Method>
    <Method Name="Execute" Id="{c1f8cc95-9b08-4af9-9fc8-404fa7cafc43}">
      <Declaration><![CDATA[METHOD Execute : BOOL
]]></Declaration>
    </Method>
    <Property Name="IsComplete" Id="{6baf7756-7931-43b3-8e45-c76877b6c151}">
      <Declaration><![CDATA[PROPERTY IsComplete : BOOL
]]></Declaration>
      <Get Name="Get" Id="{728bfb1e-0be8-4019-97ec-510ea2efbd9c}">
        <Declaration><![CDATA[]]></Declaration>
      </Get>
    </Property>
    <Property Name="IsFaulted" Id="{2536a444-d47f-484b-b637-5ea0a53e8561}">
      <Declaration><![CDATA[PROPERTY IsFaulted : BOOL
]]></Declaration>
      <Get Name="Get" Id="{1976773f-4786-4201-baac-8932f9c6b31a}">
        <Declaration><![CDATA[]]></Declaration>
      </Get>
    </Property>
    <Method Name="Reset" Id="{415e8552-6716-498f-899d-4f9399fca2db}">
      <Declaration><![CDATA[METHOD Reset : BOOL
]]></Declaration>
    </Method>
    <Property Name="StateName" Id="{17c56c01-08b8-4c64-97d1-7a1855cb36db}">
      <Declaration><![CDATA[PROPERTY StateName : STRING(40)
]]></Declaration>
      <Get Name="Get" Id="{88e93306-011a-49df-8280-89e8691160f0}">
        <Declaration><![CDATA[]]></Declaration>
      </Get>
    </Property>
  </Itf>
</TcPlcObject>