<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <Itf Name="I_DataLogger" Id="{a86bbf96-76b1-4e91-94ef-4ff83e87e23d}">
    <Declaration><![CDATA[INTERFACE I_DataLogger
]]></Declaration>
    <Method Name="LogCycleData" Id="{eaa38c8d-c6fe-43ff-920a-a531e9c8c2e0}">
      <Declaration><![CDATA[METHOD LogCycleData : BOOL
VAR_INPUT
    StationName : STRING(40);
    StepNumber  : INT;
    CycleTimeMs : LREAL;
END_VAR
]]></Declaration>
    </Method>
    <Method Name="Flush" Id="{28654dbd-a707-46ef-b583-74356eccf678}">
      <Declaration><![CDATA[METHOD Flush : BOOL
]]></Declaration>
    </Method>
    <Property Name="IsEnabled" Id="{c7345c14-3a2a-4b90-88ee-3459f0797b50}">
      <Declaration><![CDATA[PROPERTY IsEnabled : BOOL
]]></Declaration>
      <Get Name="Get" Id="{6713025c-7cec-4fc3-b407-a82aa2fad959}">
        <Declaration><![CDATA[]]></Declaration>
      </Get>
    </Property>
  </Itf>
</TcPlcObject>
