<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <Itf Name="I_HmiReportable" Id="{3561b024-12f2-4e56-b022-07218a30742a}">
    <Declaration><![CDATA[INTERFACE I_HmiReportable
]]></Declaration>
    <Property Name="StatusText" Id="{648f128e-39d0-44fe-8811-633f69f1f762}">
      <Declaration><![CDATA[PROPERTY StatusText : STRING(80)
]]></Declaration>
      <Get Name="Get" Id="{ad2f9492-d14a-4e1c-9b95-22f7fe1d21b1}">
        <Declaration><![CDATA[]]></Declaration>
      </Get>
    </Property>
    <Property Name="StateNumber" Id="{e2411eb3-9956-4e17-af30-cb2dc2e78aa4}">
      <Declaration><![CDATA[PROPERTY StateNumber : INT
]]></Declaration>
      <Get Name="Get" Id="{eaf53e28-24bb-44fd-85d1-1015c8e6619b}">
        <Declaration><![CDATA[]]></Declaration>
      </Get>
    </Property>
    <Property Name="AlarmActive" Id="{87093927-0434-4e5e-a374-6a834ab7d185}">
      <Declaration><![CDATA[PROPERTY AlarmActive : BOOL
]]></Declaration>
      <Get Name="Get" Id="{0b086a32-434a-445e-9fae-b5401263b2d6}">
        <Declaration><![CDATA[]]></Declaration>
      </Get>
    </Property>
    <Property Name="AlarmMessage" Id="{5074ebbb-e87c-4bf9-b7e0-7040a42a9810}">
      <Declaration><![CDATA[PROPERTY AlarmMessage : STRING(255)
]]></Declaration>
      <Get Name="Get" Id="{e4a425d6-5a21-4931-994a-6227c8f2f271}">
        <Declaration><![CDATA[]]></Declaration>
      </Get>
    </Property>
  </Itf>
</TcPlcObject>
